FROM maven:3.8.7 AS maven

WORKDIR /app
COPY . .
# Compile and package the application to an executable JAR
RUN mvn package -DskipTests

# For Java 17
FROM openjdk:17-jdk-alpine

ARG JAR_FILE=demo-0.0.1-SNAPSHOT.jar

WORKDIR /opt/app

COPY --from=maven /app/target/${JAR_FILE} /opt/app/

ENV PROFILE dev

EXPOSE 8080

ENTRYPOINT ["java","-jar","demo-0.0.1-SNAPSHOT.jar"]